//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Store&gt;
        ///  &lt;Products&gt;
        ///    &lt;Product id=&quot;PROD01&quot;&gt;
        ///      &lt;Title&gt;Product 1&lt;/Title&gt;
        ///      &lt;Description&gt;&lt;![CDATA[Product &lt;b&gt;1&lt;/b&gt; description]]&gt;&lt;/Description&gt;
        ///      &lt;Image&gt;prod01.gif&lt;/Image&gt;
        ///      &lt;Specs&gt;
        ///        &lt;Spec&gt;Good computer&lt;/Spec&gt;
        ///        &lt;Spec&gt;Good display&lt;/Spec&gt;
        ///        &lt;Spec&gt;Latest version&lt;/Spec&gt;
        ///      &lt;/Specs&gt;
        ///      &lt;Availability&gt;same day&lt;/Availability&gt;
        ///	&lt;/Product&gt;
        ///    &lt;Product id=&quot;PROD02&quot;&gt;
        ///      &lt;Title&gt;Product 2&lt;/Title&gt;
        ///      &lt;Description&gt;&lt;![CDAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Store&gt;
        ///  &lt;Products&gt;
        ///    &lt;Product id=&quot;PROD01&quot;&gt;
        ///      &lt;Title&gt;Product 1&lt;/Title&gt;
        ///      &lt;Description&gt;&lt;![CDATA[Product &lt;b&gt;1&lt;/b&gt; description]]&gt;&lt;/Description&gt;
        ///      &lt;Image&gt;prod01.gif&lt;/Image&gt;
        ///      &lt;Price&gt;145.12&lt;/Price&gt;
        ///      &lt;Sorting&gt;
        ///        &lt;Popular&gt;1&lt;/Popular&gt;
        ///      &lt;/Sorting&gt;
        ///    &lt;/Product&gt;
        ///    &lt;Product id=&quot;PROD02&quot;&gt;
        ///      &lt;Title&gt;Product 2&lt;/Title&gt;
        ///      &lt;Description&gt;Product 2 description&lt;/Description&gt;
        ///      &lt;Image&gt;prod01.gif&lt;/Image&gt;
        ///      &lt;Price&gt;74&lt;/Price&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
    }
}
